#!/bin/bash
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m-        TRANSLATE BY SPVPN-TH  แอดแบงค์                   -\033[0m"
echo -e "\033[0;32m-              LINEID :  BANKKISSS                        -\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
backbot=$1
[[ -z $backbot ]] && {
	IP=$(wget -qO- ipv4.icanhazip.com)
	apchon () {
		if netstat -nltp|grep 'dropbear' > /dev/null; then
			[[ ! -d /var/www/html ]] && mkdir /var/www/html
			[[ ! -d /var/www/html/backup ]] && mkdir /var/www/html/backup
			touch /var/www/html/backup/index.html
			/etc/init.d/apache2 restart
		else
			apt-get install apache2 zip -y
			sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf
			service apache2 restart
			[[ ! -d /var/www/html ]] && mkdir /var/www/html
			[[ ! -d /var/www/html/backup ]] && mkdir /var/www/html/backup
			touch /var/www/html/backup/index.html
			chmod -R 755 /var/www
			/etc/init.d/apache2 restart
		fi
	}
	fun_temp () {
		helice () {
			apchon > /dev/null 2>&1 & 
			tput civis
			while [ -d /proc/$! ]
			do
				for i in / - \\ \|
				do
					sleep .1
					echo -ne "\e[1D$i"
				done
			done
			tput cnorm
		}
		echo -ne "\033[1;33mWAIT\033[1;31m.\033[1;32m.\033[1;33m. \033[1;32m"
		helice
		echo -e "\e[1DOk"
	}
	geralink () {
		if [ -d /var/www/html/backup ]; then
			rm -rf /var/www/html/backup/backup.vps > /dev/null 2>&1
			cp $HOME/backup.vps /var/www/html/backup/backup.vps
			sleep 2
		fi
	}
	fun_temp2 () {
		helice () {
			geralink > /dev/null 2>&1 & 
			tput civis
			while [ -d /proc/$! ]
			do
				for i in / - \\ \|
				do
					sleep .1
					echo -ne "\e[1D$i"
				done
			done
			tput cnorm
		}
		echo -ne "\033[1;33mGENERATING LINK\033[1;31m.\033[1;32m.\033[1;33m. \033[1;32m"
		helice
		echo -e "\e[1DOk"
	}
	echo -e "\E[44;1;37m             Backup Manager              \E[0m"
	echo ""
	echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mสร้างไฟล์แบ็คอัพ \033[1;37m"
	echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mคืนค่าผู้ใช้ (แอดมิน) \033[1;37m"
	echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mเพิ่ม User SIMTHAI VPN\033[1;37m"
    echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mคืนค่าผู้ใช้ด้วย IP (สคริป SPVPNTH)\033[1;37m"
	echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ \033[1;37m"
	echo ""
	echo -ne "\033[1;32mWHAT DO YOU WANT TO DO\033[1;31m ?\033[1;37m : "; read opcao
	if [[ "$opcao" = '1' ]]; then
		if [ -f "/root/usuarios.db" ]
		then
			rm -rf $HOME/backup.vps > /dev/null 2>&1
			sleep 1
			tar cvf /root/backup.vps /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow > /dev/null 2>&1
			echo ""
			echo -e "\033[1;32mBACKUP SUCCESSFULLY CREATED !\033[0m"
			echo ""
			echo -ne "\033[1;32mGENERATE DOWNLOAD LINK \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read resp
			if [[ "$resp" = "s" ]]; then
				echo ""
				fun_temp
				echo ""
				fun_temp2
				echo ""
				if [ -e /var/www/html/backup/backup.vps ]; then
					if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
						echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/html/backup/backup.vps\033[0m"
					else
						echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/backup/backup.vps\033[0m"
					fi
				else
					echo -e "\033[1;32mAvailable in\033[1;31m" ~/"backup.vps\033[0m"
				fi
			else
				echo -e "\n\033[1;32mAvailable in\033[1;31m" ~/"backup.vps\033[0m"
				sleep 2
				menu
			fi
		else
			echo ""
			echo -e "\033[1;32mCreating backup...\033[0m"
			echo ""
			tar cvf /root/backup.vps /etc/shadow /etc/passwd /etc/group /etc/gshadow > /dev/null 2>&1
			sleep 2s
			echo ""
			echo -e "\033[1;33mThe file \033[1;32mbackup.vps"
			echo -e "\033[1;33mwas successfully created in the directory \033[1;31m/root\033[0m"
			echo ""
		fi
	fi
	if [[ "$opcao" = '2' ]]; then
clear 
echo  ""
echo  ""
echo  ""
echo -e "\033[1;35m { ----------------------------------------------- }  "
echo -e "\033[1;35m { -------------------SPVPN-TH-------------------- }  "
echo -e "\033[1;35m { ----------------------------------------------- }  "
echo -e "\033[1;31m { th1 }                เซิฟเวอร์ 1"
echo -e "\033[1;32m { th2 }                เซิฟเวอร์ 2 "
echo -e "\033[1;33m { th3 }                เซิฟเวอร์ 3 "
echo -e "\033[1;34m { th4 }                เซิฟเวอร์ 4 " 
echo -e "\033[1;34m { th5 }                เซิฟเวอร์ 5" 
echo -e "\033[1;34m { th6 }                เซิฟเวอร์ 6" 
echo -e "\033[1;35m { ----------------------------------------------- }  "
   
    read -p "กรอกชื่อรายการทีแบคอัพไว้ :  " -e bkup
    echo ""
    echo ""
cd /
wget -O /root/$bkup.vps http://spnet-vpn.com/backup/$bkup.vps  
		if [ -f "/root/$bkup.vps" ]
		then
			echo ""
			echo -e "\033[1;36mกำลังดำเนินการ..."
			echo ""
			sleep 2s
			cp /root/$bkup.vps /$bkup.vps
			cd /
			tar -xvf $bkup.vps
			rm /$bkup.vps
     echo "=== สำเร็จแล้ว === "
echo -e "\033[01;35m"

			echo ""
			echo -e "\033[1;36mข้ออมูลแบ็คอัพ\033[1;36m ดำเนินการสำเร็จ.\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mไฟล์ \033[1;32m$bkup.vps \033[1;33mไม่พบไฟล์แบคอัพ!\033[0m"
			echo -e "\033[1;33mตรวจสอบให้แน่ใจว่าแบ็คอัพไฟล์ \033[1;32m$bkup.vpsแล้ว\033[0m"
			echo ""
			exit
		fi
	fi
    if [[ "$opcao" = '3' ]]; then
clear 
echo  ""
echo  ""
echo  ""
echo -e "\033[1;34m"
    echo ""
    echo ""
echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ DNS ต้องเพิ่มลงคราวแฟร์ก่อน  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " dns

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ root ชื่อผู้ใช้ รูทเท่านั้น  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " root

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ รหัสผ่านเซิฟเวอร์  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " pass

curl "https://spnet-vpn.com/add_free.php?update_free=true&ip=$dns&quser=$root&qpass=$pass"


clear

			echo -e "\033[1;36mข้อมูลแบ็คอัพ\033[1;36m ดำเนินการสำเร็จ.\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mหากไม่สำเร็จโปรดตรวจสอบว่ามีการแบคอัพแล้วหรือยัง \033[1;32m\033[0m"
			echo ""
			exit
		
	fi
    	if [[ "$opcao" = '4' ]]; then
clear 
echo  ""
echo  ""
echo  ""
    read -p "กรอกไอพีที่แบ็คอัพ :  " -e bkup
    echo ""
    echo ""
cd /
wget -O /root/backup.vps http://$bkup/backup.vps  
		if [ -f "/root/$bkup.vps" ]
		then
			echo ""
			echo -e "\033[1;36mกำลังดำเนินการ..."
			echo ""
			sleep 2s
			cp /root/bankup.vps /backup.vps
			cd /
			tar -xvf backup.vps
			rm /backup.vps
			echo -e "\033[1;36mข้อมูลแบ็คอัพ\033[1;36m ดำเนินการสำเร็จ.\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mไฟล์จาก \033[1;32m$bkup \033[1;33mไม่พบไฟล์แบคอัพ!\033[0m"
			echo -e "\033[1;33mตรวจสอบให้แน่ใจว่าแบ็คอัพไฟล์จาก \033[1;32m$bkup แล้ว\033[0m"
			echo ""
			exit
		fi
	fi

	if [[ "$opcao" = '5' ]]; then
		menu
	fi
} || {
	rm /root/$bkup.vps 1>/dev/null 2>/dev/null
	tar cvf /root/$bkup.vps /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow /etc/bot 1>/dev/null 2>/dev/null
	[[ -d "/etc/SSHPlus/backups" ]] && mv /root/backup.vps /etc/SSHPlus/backups/$bkup.vps
	exit
}