#!/bin/bash

clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m-         Backup and Restore Script          -\033[0m"
echo -e "\033[0;32m-       Created by San Soe - @sansoe2021     -\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""

backup_file="/root/backup.vps"
backup_folder="/var/www/html/backup"
apache_folder="/var/www/html"

# Function to set up Apache and backup directory
setup_apache() {
    if ! dpkg -l | grep -q apache2; then
        echo -e "\033[1;32mInstalling Apache2 and Zip...\033[0m"
        apt-get update && apt-get install apache2 zip -y
        sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf
        service apache2 restart
    fi
    [[ ! -d $apache_folder ]] && mkdir -p $apache_folder
    [[ ! -d $backup_folder ]] && mkdir -p $backup_folder
    touch $backup_folder/index.html
    chmod -R 755 $apache_folder
    service apache2 restart
}

# Function to create a backup
create_backup() {
    if [ -f "/root/usuarios.db" ]; then
        echo -e "\033[1;32mCreating backup...\033[0m"
        rm -f $backup_file
        tar -cvf $backup_file /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow /etc/SSHPlus/senha > /dev/null 2>&1
        echo -e "\033[1;32mBackup created successfully!\033[0m"
        
        echo -ne "\033[1;32mGenerate download link (y/n)? \033[0m"
        read generate_link
        if [[ "$generate_link" == "y" ]]; then
            setup_apache
            cp $backup_file $backup_folder/backup.vps
            IP=$(wget -qO- ipv4.icanhazip.com)
            echo -e "\033[1;32mDownload Link: http://$IP:81/backup/backup.vps\033[0m"
        else
            echo -e "\033[1;32mBackup available at: $backup_file\033[0m"
        fi
    else
        echo -e "\033[1;31mUser database not found! Backup failed.\033[0m"
    fi
}

# Function to restore a backup
restore_backup() {
    if [ -f "$backup_file" ]; then
        echo -e "\033[1;36mRestoring backup...\033[0m"
        tar -xvf $backup_file -C / > /dev/null 2>&1
        echo -e "\033[1;36mBackup restored successfully.\033[0m"
    else
        echo -e "\033[1;31mBackup file not found!\033[0m"
    fi
}

# Main menu
echo -e "\E[44;1;37m             Backup and Restore Menu              \E[0m"
echo ""
echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCreate Backup"
echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mRestore Backup"
echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mExit"
echo ""
echo -ne "\033[1;32mChoose an option: \033[0m"
read option

case $option in
    1) create_backup ;;
    2) restore_backup ;;
    3) exit ;;
    *) echo -e "\033[1;31mInvalid option!\033[0m" ;;
esac
